In [11]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()

In [3]:
with tf.compat.v1.Session() as sess:
    a = tf.constant(5)
    b = tf.constant(3)
    c = tf.constant(2)

    d = tf.multiply(a,b)
    e = tf.add(b,c)
    f = tf.subtract(d,e)

    saida = sess.run(f)
sess.close

2024-07-30 16:10:17.666195: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:388] MLIR V1 optimization pass is not enabled


<bound method BaseSession.close of <tensorflow.python.client.session.Session object at 0x7f17f0207d60>>

In [6]:
print(saida)

10


In [7]:
print(f)

tf.Tensor(10, shape=(), dtype=int32)


In [13]:
A = tf.constant([[1,2,3],[4,5,6]])
B = tf.constant([[0,0],[1,0],[0,1]])

In [14]:
print(tf.compat.v1.Session().run(B))

[[0 0]
 [1 0]
 [0 1]]


In [15]:
resultado = tf.matmul(A,B)

In [16]:
print(tf.compat.v1.Session().run(resultado))

[[2 3]
 [5 6]]


In [19]:
print(resultado.shape) # dimensao do objeto

(2, 2)


In [34]:
x = tf.constant([0,1,0])
print(x.shape)

(3,)


In [35]:
x = tf.expand_dims(x,1)
print(x.shape)

(3, 1)


In [38]:
resultado2 = tf.matmul(A,x)

In [39]:
print(tf.compat.v1.Session().run(resultado2))

[[2]
 [5]]


In [37]:
print(x.shape)

(3, 1)
